version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=xtest_pass
      - POSTGRES_USER=xtest_user
      - POSTGRES_DB=xtest_db